[package]
name = "earwig_template_engine"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
edition = "2021"
name = "earwig_template_engine"
path = "src/main.rs"


[dependencies]
regex = "0.2"
colored = "2"